"""Add leads table for production

Revision ID: 540704652473
Revises: 20250107_0003
Create Date: 2026-01-21 23:57:34.365078

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '540704652473'
down_revision = '20250107_0003'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leads',
    sa.Column('lead_id', sa.String(length=256), nullable=False),
    sa.Column('slot_id', sa.String(length=128), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('country', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('clicked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['slot_id'], ['slots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('lead_id')
    )
    op.create_index(op.f('ix_leads_country'), 'leads', ['country'], unique=False)
    op.create_index(op.f('ix_leads_fetched_at'), 'leads', ['fetched_at'], unique=False)
    op.create_index(op.f('ix_leads_slot_id'), 'leads', ['slot_id'], unique=False)
    op.create_index(op.f('ix_leads_status'), 'leads', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_leads_status'), table_name='leads')
    op.drop_index(op.f('ix_leads_slot_id'), table_name='leads')
    op.drop_index(op.f('ix_leads_fetched_at'), table_name='leads')
    op.drop_index(op.f('ix_leads_country'), table_name='leads')
    op.drop_table('leads')
    # ### end Alembic commands ###
